# Generated by Django 4.2.13 on 2026-02-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('cafe_type', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('is_open', models.BooleanField(default=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cafes',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(unique=True)),
                ('road_type', models.CharField(blank=True, max_length=50)),
                ('geometry', models.TextField()),
            ],
            options={
                'db_table': 'roads',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('picture_url', models.URLField(blank=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_number', models.IntegerField(unique=True)),
                ('population', models.IntegerField()),
                ('households', models.IntegerField()),
                ('area_sqkm', models.FloatField()),
                ('population_density', models.FloatField()),
                ('boundary', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wards',
            },
        ),
    ]
